In [1]:
import numpy as np
msr = np.load('UKCP18/group1-wildfires/UK_MSR.npy')

The monthly severity ratings.

In [2]:
msr.shape

(1200, 112, 82)

In [4]:
msr.size

11020800

In [14]:
# Testing out the shapes of arrays and the reshape tool
a = np.array([[[1, 2,3], [4,5,6]], [[7, 8,9], [10,11,12]]])
a.shape

(2, 2, 3)

In [17]:
np.reshape(a, (4, 3))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [19]:
a.shape[0]*a.shape[1]

4

In [21]:
# Time x Lat x Long - the matrices are lat x long, and each matrix has the values for a different time (m x r x c)
msr2 = np.reshape(msr, (msr.shape[0]*msr.shape[1], msr.shape[2]))

In [22]:
msr2.shape

(134400, 82)

In [36]:
# Means within matrices
a.mean(axis = 2)
# By row/latitude

array([[ 2.,  5.],
       [ 8., 11.]])

In [38]:
b = np.array([[[1, 2,3], [4,5,6]], [[7, 8,9], [10,11,12]],[[1, 1,2], [2,2,1]]])
b

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[ 1,  1,  2],
        [ 2,  2,  1]]])

In [48]:
c = np.reshape(b, (3, 6))

In [46]:
# Reshaping the data to prepare it for taking the averages
avgprep = np.reshape(msr, (msr.shape[0], msr.shape[1]*msr.shape[2]))

In [47]:
avgprep.shape

(1200, 9184)

In [49]:
c

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [ 1,  1,  2,  2,  2,  1]])

In [52]:
# axis = 0 averages over the columns, axis = 1 averages across the rows
c.mean(axis = 0)

array([3.        , 3.66666667, 4.66666667, 5.33333333, 6.        ,
       6.33333333])

In [53]:
# Averages
avgMSR = avgprep.mean(axis = 1)

In [54]:
avgMSR.shape

(1200,)

In [59]:
import pandas as pd

In [83]:
DF = pd.DataFrame(avgMSR)

In [92]:
DF.to_csv("MSRstats.csv")

In [73]:
maxMSR = np.amax(avgprep,axis = 1)

In [84]:
maxMSR.shape
DF.insert(1,'max',maxMSR)

In [86]:
# .columns =['Name', 'Code', 'Age', 'Weight']
DF.columns = ['avg','max']

In [87]:
DF

avg        max
0     0.056218   0.651337
1     0.035904   0.342417
2     0.046693   0.211206
3     0.082837   0.526890
4     0.072268   0.328392
...        ...        ...
1195  0.450419   5.820038
1196  0.688108  11.439051
1197  1.180219   7.153612
1198  0.315918   2.599028
1199  0.294485   3.029814

[1200 rows x 2 columns]

In [88]:
DF.insert(0,'min',np.amin(avgprep,axis = 1))

In [89]:
DF

min       avg        max
0     1.339783e-08  0.056218   0.651337
1     3.844820e-09  0.035904   0.342417
2     1.075952e-09  0.046693   0.211206
3     1.107366e-07  0.082837   0.526890
4     1.483430e-09  0.072268   0.328392
...            ...       ...        ...
1195  1.844783e-06  0.450419   5.820038
1196  4.318208e-04  0.688108  11.439051
1197  2.755359e-03  1.180219   7.153612
1198  5.392784e-06  0.315918   2.599028
1199  2.334236e-06  0.294485   3.029814

[1200 rows x 3 columns]

In [90]:
DF.insert(2,'median',np.median(avgprep,axis = 1))

In [91]:
DF

min       avg    median        max
0     1.339783e-08  0.056218  0.037346   0.651337
1     3.844820e-09  0.035904  0.022011   0.342417
2     1.075952e-09  0.046693  0.035521   0.211206
3     1.107366e-07  0.082837  0.056333   0.526890
4     1.483430e-09  0.072268  0.067576   0.328392
...            ...       ...       ...        ...
1195  1.844783e-06  0.450419  0.086525   5.820038
1196  4.318208e-04  0.688108  0.240566  11.439051
1197  2.755359e-03  1.180219  0.502825   7.153612
1198  5.392784e-06  0.315918  0.162854   2.599028
1199  2.334236e-06  0.294485  0.167000   3.029814

[1200 rows x 4 columns]

In [94]:
DF2 = pd.DataFrame(avgprep)
DF2.to_csv("MSRfull.csv")

In [95]:
avgprep[1:10,1:10]

array([[0.01301903, 0.0192043 , 0.02682222, 0.03279812, 0.03865036,
        0.04983229, 0.05647559, 0.06288139, 0.07202538],
       [0.07989238, 0.08039323, 0.07871091, 0.07234357, 0.06832338,
        0.05640099, 0.05333247, 0.05432268, 0.05888513],
       [0.33725275, 0.33957639, 0.3403499 , 0.33723084, 0.33867401,
        0.33465815, 0.30726139, 0.30107887, 0.30322443],
       [0.15418479, 0.15176214, 0.14557478, 0.1366242 , 0.14259928,
        0.15284962, 0.15771345, 0.15493935, 0.14248729],
       [0.6056433 , 0.60728584, 0.60724597, 0.57896391, 0.58007064,
        0.53707064, 0.59219985, 0.61977849, 0.60412888],
       [0.1198847 , 0.11837104, 0.11338929, 0.1124965 , 0.11145137,
        0.09628584, 0.09370107, 0.09417435, 0.1031314 ],
       [0.89932215, 0.86986301, 0.63333967, 0.57688994, 0.60765692,
        0.66464113, 0.83439664, 0.91690591, 0.91913466],
       [1.13213513, 0.99530231, 0.9634782 , 0.813339  , 0.82329238,
        0.82144869, 0.8500839 , 0.78026178, 0.78240462],


In [156]:
# Vector of extreme values
extreme = np.sum(avgprep > 6.16, axis = 1)

In [157]:
# Vector of high values
high = np.sum((avgprep > 1.82) & (avgprep <= 6.16), axis = 1)

In [158]:
# Vector of medium values
medium = np.sum((avgprep > 0.46) & (avgprep <= 1.82), axis = 1)

In [159]:
# Vector of low values
low = np.sum((avgprep > 0.1) & (avgprep <= 0.46), axis = 1)

In [160]:
# Vector of very low values
verylow = np.sum(avgprep <= 0.1, axis = 1)

In [161]:
# Checking that the columns all sum to the right number of points
(min(verylow+low+medium+high+extreme),max(verylow+low+medium+high+extreme))

(9184, 9184)

In [162]:
props = np.column_stack((verylow,low,medium,high,extreme))
props = pd.DataFrame(props)

In [164]:
props.columns = ['verylow','low','medium','high','extreme']

In [165]:
props.to_csv("MSRprops2.csv")